### ISSUE TITLE
Develop an Alarm Clock

### ISSUE THREAD

**Issue by Kabhishek18** [Kabhishek18/python_project#1]

**Comment by Kabhishek18** [comment]
Develop an Alarm Clock
This project requires good knowledge of Python and GUI (Graphic User Interface). Python when combined with Tkinter provides a fast and easy way to create GUI applications. Tkinter provides a powerful object-oriented interface to the Tk GUI toolkit. All the modules used need not be downloaded beforehand like the other libraries like NumPy, thus this project will be user friendly and accessible in any virtual environment used for python programming.

**Comment by tanya4067** [comment]
created a simple alarm clock, please check and review!
